# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/java/poi"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/camel/disk_monitor"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/camel/disk_monitor_msgq"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/camel/dtaq_to_kafka"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/camel/msgq_to_email"
    schedule:
      interval: "daily"
