<?php $this->layout('layout::default', ['title' => 'Plants']) ?>

<div class="mb-3">
    <button class="btn btn-primary" data-toggle="modal" data-target="#ModalSavePlant"><i class="fa fa-plus"></i> Add plant</button>
</div>

<table id="TablePlants" class="table table-striped table-bordered" style="width:100%">
    <thead>
    <tr>
        <th>Actions</th>
        <th>ID</th>
        <th>Name</th>
        <th>Nickname</th>
        <th>Wiki</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
</table>

<div class="modal fade" id="ModalSavePlant" tabindex="-1" aria-labelledby="ModalSavePlantLabel" aria-hidden="true">
    <div class="modal-dialog">
        <form id="FormSavePlant">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="ModalSavePlantLabel">Save New Plant</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-inputs-loading d-none">
                        <div class="spinner-border" role="status">
                            <span class="sr-only">Loading...</span>
                        </div>
                    </div>
                    <div class="form-inputs">
                        <input type="hidden" value="0" id="id" name="id">
                        <div class="form-group">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name" required>
                        </div>
                        <div class="form-group">
                            <label for="nickname" class="col-form-label">Nickname:</label>
                            <input type="text" class="form-control" id="nickname" name="nickname">
                        </div>
                        <div class="form-group">
                            <label for="wiki" class="col-form-label">Wikipedia URL:</label>
                            <input type="text" class="form-control" id="wiki" name="wiki" required>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </form>
    </div>
</div>

<?php $this->push('javascript') ?>
<script src="/assets/scripts/plants.js"></script>
<?php $this->end() ?>