{
 "title": "SysStatus-master",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "System Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System ASP Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "SYSTEM_ASP_USED", "type": "timeserie" }
   ]
  },
  {
   "title": "Jobs in System",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "TOTAL_JOBS_IN_SYSTEM", "type": "timeserie" },
    { "target": "ACTIVE_JOBS_IN_SYSTEM", "type": "timeserie" },
    { "target": "INTERACTIVE_JOBS_IN_SYSTEM", "type": "timeserie" },
    {
     "target": "TEMPORARY_JOB_STRUCTURES_AVAILABLE",
     "type": "timeserie"
    },
    {
     "target": "PERMANENT_JOB_STRUCTURES_AVAILABLE",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Temp Storage Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "target": "CURRENT_TEMPORARY_STORAGE", "type": "timeserie" },
    { "target": "MAXIMUM_TEMPORARY_STORAGE_USED", "type": "timeserie" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "target": "AVERAGE_CPU_UTILIZATION", "type": "timeserie" },
    { "target": "ELAPSED_CPU_USED", "type": "timeserie" },
    { "target": "CONFIGURED_CPUS", "type": "timeserie" }
   ]
  },
  {
   "title": "HTTP Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Server Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "target": "HTTP", "type": "table" }
   ]
  }
 ]
}